actions:

  - type: arm # 动作类型: arm 或 gripper
    name: "左臂lift_to_side" # 动作名称（用于日志显示）
    arm: left # 机械臂: left 或 right
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    positions:
      [
        -0.07419699397268609,
        -1.4459830624856949,
        0.13179980163271487,
        0.07000076295109459,
        -0.2172503242542163,
        -0.006294346532387252,
        -0.21572442206454667,
      ]
    wait_time: 2.0 # 等待时间（秒），完成后等待多久再执行下一个动作

  - type: arm
    name: "右臂lift_to_side"
    arm: right
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    positions:
      [
          0.005149919890135024,
          1.4269092851148244,
          -0.0001907377737087046,
          0.10128175783932214,
          -0.032997634851605895,
          -0.10433356221866141,
          0.052071412222476354,
      ]
    wait_time: 2.0

  - type: arm
    name: "右臂put_gun_before"
    arm: right
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    positions:
      [
          0.6784542610818658,
          0.4793240253299782,
          -0.16727702754253393,
          0.9782940413519494,
          -1.3529030289158452,
          0.02613107499809253,
          0.24586099031052022,
      ]
    wait_time: 2.0


  - type: arm # 动作类型: arm 或 gripper
    name: "左臂put_gun_before" # 动作名称（用于日志显示）
    arm: left # 机械臂: left 或 right
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    positions:
      [
          -1.1045624475471119,
          -0.5430304417486838,
          1.0046158541237507,
          0.18825818265049143,
          0.45567254139009883,
          0.14629587243457642,
          -0.6193255512321674,
      ]
    wait_time: 2.0 # 等待时间（秒），完成后等待多久再执行下一个动作

  - type: arm # 动作类型: arm 或 gripper
    name: "左臂put_gun" # 动作名称（用于日志显示）
    arm: left # 机械臂: left 或 right
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    positions:
      [
          -0.9550240329594875,
          -0.21877622644388595,
          0.9943160143434806,
          0.4015030136568267,
          1.5077821011673151,
          0.3374151216906984,
          -0.1203555352101926,
      ]
    wait_time: 2.0 # 等待时间（秒），完成后等待多久再执行下一个动作

  - type: arm
    name: "右臂put_gun"
    arm: right
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    positions:
      [
          1.0828183413443195,
          0.09746700236514805,
          -1.1938277256427856,
          0.13904783703364565,
          -1.2628747997253367,
          -0.304608224612803,
          0.23365377279316313,
      ]
    wait_time: 45

  - type: arm # 动作类型: arm 或 gripper
    name: "左臂put_gun_before" # 动作名称（用于日志显示）
    arm: left # 机械臂: left 或 right
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    positions:
      [
          -1.1045624475471119,
          -0.5430304417486838,
          1.0046158541237507,
          0.18825818265049143,
          0.45567254139009883,
          0.14629587243457642,
          -0.6193255512321674,
      ]
    wait_time: 2.0 # 等待时间（秒），完成后等待多久再执行下一个动作

  - type: arm
    name: "右臂put_gun_before"
    arm: right
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    positions:
      [
          0.6784542610818658,
          0.4793240253299782,
          -0.16727702754253393,
          0.9782940413519494,
          -1.3529030289158452,
          0.02613107499809253,
          0.24586099031052022,
      ]
    wait_time: 2.0


  - type: arm # 动作类型: arm 或 gripper
    name: "左臂lift_to_side" # 动作名称（用于日志显示）
    arm: left # 机械臂: left 或 right
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    positions:
      [
        -0.07419699397268609,
        -1.4459830624856949,
        0.13179980163271487,
        0.07000076295109459,
        -0.2172503242542163,
        -0.006294346532387252,
        -0.21572442206454667,
      ]
    wait_time: 2.0 # 等待时间（秒），完成后等待多久再执行下一个动作

  - type: arm
    name: "右臂lift_to_side"
    arm: right
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    positions:
      [
          0.005149919890135024,
          1.4269092851148244,
          -0.0001907377737087046,
          0.10128175783932214,
          -0.032997634851605895,
          -0.10433356221866141,
          0.052071412222476354,
      ]
    wait_time: 2.0


  - type: arm
    name: "左臂回到零位"
    arm: left
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    wait_time: 2.0

  - type: arm
    name: "右臂回到零位"
    arm: right
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    wait_time: 2.0
