actions:

  - type: arm # 动作类型: arm 或 gripper
    name: "左臂lift_to_side" # 动作名称（用于日志显示）
    arm: left # 机械臂: left 或 right
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    positions:
      [
        -0.0001907377737087046,
        -0.9950789654383154,
        0.02536812390325771,
        0.08106355382619945,
        0.0005722133211261138,
        0.22182803082322344,
        0.032616159304188486,
      ]
    wait_time: 2.0 # 等待时间（秒），完成后等待多久再执行下一个动作

  - type: arm
    name: "右臂lift_to_side"
    arm: right
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    positions:
      [
        0.12188143739986224,
        1.359388113221943,
        0.3656443121995867,
        0.14782177462424606,
        0.0913633936064695,
        0.007820248722056888,
        0.3404669260700377,
      ]
    wait_time: 2.5


  - type: arm # 动作类型: arm 或 gripper
    name: "左臂put_gun_before" # 动作名称（用于日志显示）
    arm: left # 机械臂: left 或 right
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    positions:
      [
          -0.778400854505227,
          -0.6372549019607856,
          1.4524681467917908,
          0.0036240177004653873,
          -0.20923933775845072,
          0.4537651636530118,
          -0.33436331731136093,
      ]
    wait_time: 2.0 # 等待时间（秒），完成后等待多久再执行下一个动作

  - type: arm # 动作类型: arm 或 gripper
    name: "左臂put_gun" # 动作名称（用于日志显示）
    arm: left # 机械臂: left 或 right
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    positions:
      [
          -0.8478294041351955,
          -0.14324406805523715,
          0.9599832150759138,
          0.003242542153047978,
          1.1411841000991831,
          0.4575799191271859,
          0.18902113374532625,
      ]
    wait_time: 2.0 # 等待时间（秒），完成后等待多久再执行下一个动作
  - type: arm # 动作类型: arm 或 gripper
    name: "左臂put_gun_before" # 动作名称（用于日志显示）
    arm: left # 机械臂: left 或 right
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    positions:
      [
          -0.778400854505227,
          -0.6372549019607856,
          1.4524681467917908,
          0.0036240177004653873,
          -0.20923933775845072,
          0.4537651636530118,
          -0.33436331731136093,
      ]
    wait_time: 2.0 # 等待时间（秒），完成后等待多久再执行下一个动作


  - type: arm # 动作类型: arm 或 gripper
    name: "左臂lift_to_side" # 动作名称（用于日志显示）
    arm: left # 机械臂: left 或 right
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    positions:
      [
        -0.0001907377737087046,
        -0.9950789654383154,
        0.02536812390325771,
        0.08106355382619945,
        0.0005722133211261138,
        0.22182803082322344,
        0.032616159304188486,
      ]
    wait_time: 2.0 # 等待时间（秒），完成后等待多久再执行下一个动作
  - type: arm
    name: "左臂回到零位"
    arm: left
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    wait_time: 2.0

  - type: arm
    name: "右臂回到零位"
    arm: right
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    wait_time: 2.0
